### PR TITLE
Update the firmware to a Universal Hex with v1.0.1 and v2.0.0-beta.5.

### PR DESCRIPTION
**Pull request by carlosperate**
Last step required for PR https://github.com/ntoll/uflash/pull/72 (as mentioned in https://github.com/ntoll/uflash/pull/72#discussion_r581307928).

### CODE REVIEW

**Comment by ntoll** [comment]
OK.... happy for me to cut/push a new release of uflash to PyPI..? @carlosperate

**Comment by carlosperate** [comment]
Yes let's do it!

At some point I'd like to create a PR to add black (with black formatting) to the uFlash project, this is to make comparisons to the Mu version easier as Mu is blackified, but that can happen after the uFlash v2 release.

**Comment by ntoll** [comment]
https://pypi.org/project/uflash/ :-)

**Comment by carlosperate** [comment]
🎉 🥳

**Pull request merged**
