### PR TITLE
Added keepname argument and used filename in output message

### PR DESCRIPTION
**Pull request by ScottDWebster**
I added a new command line argument (-k, --keepname) to preserve the root filename of the python script.
I modified the output message to use the input filename instead of "Python" when path_to_python exists.
I updated the documentation to reflect the above changes.
I added keepname related tests.  Let me know if my tests make sense and/or are sufficient.

### CODE REVIEW

**Comment by ntoll** [comment]
Hi, umm.... you've added a whole bunch of files that are not part of this project. Please remove them from the PR. Thanks! :-)

**Comment by ScottDWebster** [comment]
Oop, sorry.  I have no idea what happened, but somehow a number of pdf files got generated in the directory.  At some point, git warned of untracked files and I added them without checking what they were.  They're all gone now.

**Comment by ScottDWebster** [comment]
I've created a new script called [hexify](https://github.com/ScottDWebster/uflash/blob/hexify/hexify.py) to allow for multiple input files (it loads uflash as a module).  Now I'm thinking that maybe keepname should be removed from the command line arguments and just left as an argument to flash().  My hexify script always sets keepname to true.  It might be less confusing to have the functions of flashing to the microbit (uflash) vs. generating hex files on the local filesystem (hexify) completely separated.  What do you think?

**Comment by ScottDWebster** [comment]
Use my other pull request instead.  I'll close this one.

**Pull request closed without merging**
