### PR TITLE
Update microbit firmware to v1.0.0-rc1

### PR DESCRIPTION
**Pull request by carlosperate**
There has been a change in the hex file, before it used to end with:

```
:040000050001993528
:00000001FF
```

Now it add some data to the UICR, so after the MicroPython runtime we have 3 extra lines before the last two:

```
:020000041000EA
:1010C0007CB0EE17FFFFFFFF0A0000000000E10008
:0C10D000FFFFFFFF750C03000000000094
:040000050001993528
:00000001FF
```

This PR updates uFlash to take that in consideration in its calculations.

### CODE REVIEW

**Comment by ntoll** [comment]
Awesome... checking now. :-) Thank you

**Comment by carlosperate** [comment]
I've separated the commit in two so that you can actually see the changes in uFlash (GitHub complains when updating the firmware because the change is too big):
https://github.com/carlosperate/uflash/commit/2316827f5f0d92e44d5e7642147567447058d7c8

**Comment by ntoll** [comment]
OK... I've just checked it in the following ways:

* The tests all pass.
* When run from the command line uflash appends the script in the right way.
* When flashed from Mu (with the version containing an embedded script from step 2) the newly copied `main.py` takes precedence.
* When re-flashed with an *old* version of MicroPython, the semver check kicks in if I try to flash with this version of MicroPython.
* I re-tried the `is_touched` functionality (see: https://github.com/bbcmicrobit/micropython/issues/529), but this doesn't appear fixed. :-( Perhaps test this again? Fix in 1.0.0 final.

**Comment by ntoll** [comment]
OK... scratch that... un-plugging and plugging back in again made it work. No idea why... but that's good enough for me. ;-)

**Pull request merged**
